POST https://to-do-list-4md4.onrender.com/agenda
Content-Type:  application/json

{
    "date": "02/03/2004",
    "description": "asd",
    "duration": 24
}

###

GET https://to-do-list-4md4.onrender.com/agenda


###

PUT https://to-do-list-4md4.onrender.com/agenda/ea5d751e-8c59-40cd-a8c6-4bc927c77e69
Content-type:  application/json

{
    "date": "02/03/2004",
    "description": "Nascimento",
    "duration": 24
}

###

DELETE https://to-do-list-4md4.onrender.com/agenda/2b4251d8-940c-4208-8bb3-b506256f6c50
